Mb 518
mindbox-moscow/php-sdk pull request #15
Opened 2020-10-27 15:16 UTC by MaximBurcev

2020-10-28 12:32 UTC, itsyrulnikov requested changes

2020-10-28 12:32 UTC, itsyrulnikov commented on src/DTO/V2/Requests/LineRequestDTO.php
>          $this->setField('sku', $sku);
Договаривались выпилить sku из SDK вообще

2020-10-28 12:32 UTC, itsyrulnikov commented on src/Helpers/CustomerHelper.php
> +    public function register(CustomerRequestDTO $customer, $operationName, $addDeviceUUID = true, $isSync)
я думаю, что скин должен передавать не параметром в метод, а должны быть разные методы для синк и асинк, т.к. у них сигнатуры могут отличаться (для синка важен ответ, для асинка – нет)

2020-10-28 12:32 UTC, itsyrulnikov commented on src/Helpers/CustomerHelper.php
> +        return $this->client->prepareRequest('POST', $operationName, $operation, '', [], $isSync, $addDeviceUUID);
авторизацию никогда не хотим синхронно передавать

2020-10-28 12:32 UTC, itsyrulnikov commented on src/Helpers/OrderHelper.php
> +    public function CreateAuthorizedOrder(OrderCreateRequestDTO $order, $operationName)
Аналогично в название нужно вынести Sync/Async, станет намного понятнее

2020-11-05 11:28 UTC, MaximBurcev commented
Это "Договаривались выпилить sku из SDK вообще" и "авторизацию никогда не хотим синхронно передавать" я доработал.
Остальное пока решили не делать.

2020-11-06 17:43 UTC, itsyrulnikov approved these changes

2020-11-15 15:30 UTC, merged